version: '3'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3001:8080"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      n8n:
        condition: service_started

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      # Database configuration for persistence
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      
      # Web interface authentication
      - N8N_BASIC_AUTH_ACTIVE=false
      
      # Security configuration
      - N8N_SECURE_COOKIE=false
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      
      # Webhook and API authentication
      - N8N_WEBHOOK_TEST_URL=${N8N_HOST:-http://n8n:5678}
      - N8N_WEBHOOK_URL=${N8N_HOST:-http://n8n:5678}
      - N8N_WEBHOOK_SECRET=${N8N_WEBHOOK_SECRET}
      
      # General configuration
      - N8N_PORT=5678
      
      # AI Provider API Keys - explicitly set with actual values
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      
      # Supabase credentials
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      
      # Credentials encryption
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      
      # Debug mode for troubleshooting
      - N8N_LOG_LEVEL=debug
    volumes:
      - ./.n8n:/home/node/.n8n
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge 