version: '3'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    volumes:
      - ./backend:/app
    networks:
      - app-network

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      # Database configuration for persistence
      - DB_TYPE=sqlite
      - DB_SQLITE_PATH=/home/node/.n8n/database.sqlite
      
      # Web interface authentication (optional in development)
      - N8N_BASIC_AUTH_ACTIVE=false
      
      # Webhook and API authentication
      - N8N_WEBHOOK_TEST_URL=http://localhost:5678/
      - N8N_WEBHOOK_URL=${N8N_HOST:-http://localhost:5678}
      - N8N_WEBHOOK_SECRET=${N8N_WEBHOOK_SECRET}
      
      # General configuration
      - N8N_HOST=${N8N_HOST:-http://localhost:5678}
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=${N8N_HOST:-http://localhost:5678}
      
      # Optional: Set these for production
      # - N8N_BASIC_AUTH_USER=admin
      # - N8N_BASIC_AUTH_PASSWORD=${N8N_API_KEY}
    volumes:
      - ./.n8n:/home/node/.n8n
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 