name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Configure npm for Font Awesome
      run: |
        echo "@fortawesome:registry=https://npm.fontawesome.com/" > ~/.npmrc
        echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_TOKEN }}" >> ~/.npmrc
      
    - name: Install Dependencies
      run: |
        cd frontend
        npm ci --legacy-peer-deps
        
    - name: Build
      run: |
        cd frontend
        npm run build 